---
title: "Read Obits"
author: "Alan Jackson"
date: "July 20, 2018"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(rvest) # for reading html
library(stringr) # string functions
library(lubridate) # date functions

knitr::opts_chunk$set(echo = TRUE)
```

## Use Obits as a death rate proxy

To get an estimate of very recent death rates, use the county paper obits. 

https://www.wilsoncountynews.com/news/2018-06-27/Funeral_Notices
xpath=

//*[contains(concat( " ", @class, " " ), concat( " ", "article-content", " " ))]

```{r read obits}

#  Read in names, birth and death dates from obits

folder <- "file:///home/ajackson/Dropbox/Rprojects/WilsonCountyGunStudy/"
input <- "Funeral_Notices_Wilson_County_News.html"

#   regular expressions for dates
born <- "\\d{0,2}-?\\d{0,2}-?\\d{4} ?(\u2014|\u2013|--) ?"
died <- "( ?(--|\u2014|\u2013) ?\\d{1,2}-\\d{1,2}-\\d{4})|(\u2022 ?\\d{1,2}-\\d{1,2}-\\d{4} ?\u2022)"
died <- " ?(--|\u2014|\u2013) ?\\d{1,2}-\\d{1,2}-\\d{4}"
mindead <- mdy("1/1/2015")

df <- read_html(input) %>%
  html_nodes(xpath='//*[contains(concat( " ", @class, " " ), concat( " ", "article-content", " " ))]') %>%
  html_text() %>%
  data.frame(stringsAsFactors = FALSE) %>%
  rename(input=".") %>%
  mutate(name=str_trim(str_remove_all(str_remove_all(input,"[\\t\\n]"), "(Free|\\d).*$"))) %>%
  mutate(born=str_trim(str_remove(str_extract(input, born),"(\u2014|\u2013|--)"))) %>%
  mutate(died=str_trim(str_remove_all(str_extract(input, died),"(\u2014|\u2013|--|\u2022)"))) %>%
  select(name, born, died) %>%
  mutate(born=mdy(born), died=mdy(died)) %>%
  mutate(died=if_else(died<mindead, as.Date(NA), died)) %>%
  mutate(age=round((died-born)/365.2422, 2))
  
```

##  Do some sanity checks and analysis on obit data


```{r}

summary(df)

df %>%
  ggplot(aes(x=died, y=age)) +
  geom_point()


```

##    Aggregate into 25 year age ranges, and quarterly dates, then plot

```{r plot quarterly aggregates}

dfnew <- df %>%
  na.omit() %>%
  mutate(qtr=as.yearqtr(died), 
         agegrp=as.integer(age/25)) %>%
  group_by(agegrp, qtr) %>%
  summarize(agegroup=n()) %>%
  mutate(normage=agegroup/sum(agegroup))
totals <- dfnew %>%
  summarize(agetot=sum(agegroup))
dfnew %>%
  ggplot(aes(x=qtr, y=normage, fill=agegrp, group=agegrp)) +
  geom_bar(stat="identity", position=position_dodge()) +
  scale_x_yearqtr(format = "%YQ%q") +
  scale_fill_continuous(type = "viridis")

```

