---
title: "Read Gun Permit Data"
author: "Alan Jackson"
date: "July 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tabulizer)

knitr::opts_chunk$set(echo = TRUE)
```

## Here be files by zipcode, with varying names...

http://www.dps.texas.gov/RSD/LTC/Reports/2014Calendar/byZipcode/17LicenseApplicationsIssued.pdf

http://www.dps.texas.gov/rsd/LTC/reports/2010Calendar/ByZipCode/CY10ZipCodeLicApplIssued.pdf

http://www.dps.texas.gov/rsd/LTC/reports/2009Calendar/ByZipCode/CY09ZipLicAppsIssued.pdf

```{r read by zip, eval=FALSE}
#   Download all the pdfs

output_folder <- "~/Dropbox/Rprojects/WilsonCountyGunStudy/GunPermits"
for (year in 1997:2017) {
  if (year>2010) {
  url <- paste0("http://www.dps.texas.gov/RSD/LTC/Reports/",year,"Calendar/byZipcode/17LicenseApplicationsIssued.pdf")
  }
  else if (year == 2010) {
  url <- paste0("http://www.dps.texas.gov/RSD/LTC/Reports/",year,"Calendar/byZipcode/CY",substr(year,3,4),"ZipCodeLicApplIssued.pdf")
  }
  else {
  url <- paste0("http://www.dps.texas.gov/RSD/LTC/Reports/",year,"Calendar/byZipcode/CY",substr(year,3,4),"ZipLicAppsIssued.pdf")
  }
  outfile <- paste0("LicenseApplicationsIssued_by_Zip",year,".pdf")
  m <- download(url, output_folder, outfile) 
  print(m)
}

```

## Here be files by county, with varying names...

http://www.dps.texas.gov/RSD/LTC/Reports/2014Calendar/byCounty/25LicenseApplicationsIssued.pdf

http://www.dps.texas.gov/rsd/LTC/reports/2010Calendar/ByCounty/CY10CountyLicApplIssued.pdf

http://www.dps.texas.gov/rsd/LTC/reports/2009Calendar/ByCounty/CY09CountyLicAppsIssued.pdf

```{r read by county, eval=FALSE}
#   Download all the pdfs

output_folder <- "~/Dropbox/Rprojects/WilsonCountyGunStudy/GunPermits"
for (year in 1997:2017) {
  if (year>2010) {
  url <- paste0("http://www.dps.texas.gov/RSD/LTC/Reports/",year,"Calendar/byCounty/25LicenseApplicationsIssued.pdf")
  }
  else if (year == 2010) {
  url <- paste0("http://www.dps.texas.gov/RSD/LTC/Reports/",year,"Calendar/byCounty/CY",substr(year,3,4),"CountyLicApplIssued.pdf")
  }
  else {
  url <- paste0("http://www.dps.texas.gov/RSD/LTC/Reports/",year,"Calendar/byCounty/CY",substr(year,3,4),"CountyLicAppsIssued.pdf")
  }
  outfile <- paste0("LicenseApplicationsIssued_by_County",year,".pdf")
  m <- download(url, output_folder, outfile) 
  print(m)
}

```

##  Parse the County PDF's

Years 2011 and 2012 were stored as images and not text in the pdf's, so that will take more work.

```{r parse county pdfs}

parse_county <- function(path, year){
  options(stringsAsFactors = FALSE)
  
  final <- data.frame(Year=character(),
                      County=character(),
                      Applicants=numeric(),
                      Percent=numeric(),
                      stringsAsFactors = FALSE)
  
  a <- extract_tables(path)
  skip <- 2
  if (year==2006|year==2007) {skip <- 3}
  if (year==2014) {skip <- 4}
  tnum <- 1:3  # table numbers to grab
  if (year==2014) {tnum <- c(1,3,5)}
  
  for (i in tnum){
    temp <- as.data.frame(a[[i]][skip:nrow(a[[i]]),1:3], stringsAsFactors = FALSE)
    names(temp) <- c("County", "Applicants", "Percent")
    temp <- cbind(Year=as.character(year), temp)
    temp$Applicants <- as.numeric(gsub(",","",temp$Applicants))
    temp$Percent <- as.numeric(gsub("%","",temp$Percent))
    final <- bind_rows(final, temp)
    
    temp <- as.data.frame(a[[i]][skip:nrow(a[[i]]),4:6], stringsAsFactors = FALSE)
    names(temp) <- c("County", "Applicants", "Percent")
    temp <- cbind(Year=as.character(year), temp)
    temp$Applicants <- as.numeric(gsub(",","",temp$Applicants))
    temp$Percent <- as.numeric(gsub("%","",temp$Percent))
    final <- bind_rows(final, temp)
  }
  if (year != 2014) {
    temp <- as.data.frame(a[[4]][skip:nrow(a[[4]]),1:3], stringsAsFactors = FALSE)
    names(temp) <- c("County", "Applicants", "Percent")
    temp <- cbind(Year=as.character(year), temp)
    temp$Applicants <- as.numeric(gsub(",","",temp$Applicants))
    temp$Percent <- as.numeric(gsub("%","",temp$Percent))
    final <- bind_rows(final, temp)
  }
  
  return(final)
}

final <- data.frame(Year=character(),
                    County=character(),
                    Applicants=numeric(),
                    Percent=numeric(),
                    stringsAsFactors = FALSE)

path <- "~/Dropbox/Rprojects/WilsonCountyGunStudy/GunPermits/LicenseApplicationsIssued_by_County"
for (year in c(1997:2010,2013:2017)) {
  print(paste0("parse ",year))
  a <- parse_county(paste0(path,year,".pdf"), year)
  final <- bind_rows(final, a)
}


```



